### ISSUE TITLE
[aux] Implements functionalRequest() 

### ISSUE THREAD

**Issue by fabgio** [mvalla/openwebnet4j#32]
[aux] implement functionalRequest()  which is responsible to generate OpenWebNet messages based on  each  Auxiliary WHAT type

**Comment by mvalla** [comment]
is this issue still needed? otherwise shall I close it?

**Comment by fabgio** [comment]
You can close it

**Comment by mvalla** [comment]
closing this issue as the suggested method is not needed for the AUX implementation
